name: 'Publish chart to KubeSphere'
description: 'Used for pull request helm chart to Kubesphere'
inputs:
  chart_dir:
    description: 'Helm chart path from you current directory'
    required: true
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  pull_request_reviewers:
    description: 'Pull request reviewers users'
    required: false
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.chart_dir }}
    - ${{ inputs.user_email }}
    - ${{ inputs.user_name }}
    - ${{ inputs.pull_request_reviewers }}
branding:
  icon: 'git-commit'
  color: 'green'